"use client"

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, Upload, Sparkles, Loader2, Check, X, RefreshCw } from 'lucide-react'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { ZoneMapper, Zone } from '@/components/zone-mapper'

// Types de compteurs
const METER_TYPES = [
  { value: 'water_general', label: 'Eau - Général', icon: '💧', unit: 'm³' },
  { value: 'water_passage', label: 'Eau - Passage', icon: '🚿', unit: 'm³' },
  { value: 'electricity', label: 'Électricité', icon: '⚡', unit: 'kWh' },
  { value: 'gas', label: 'Gaz', icon: '🔥', unit: 'm³' },
  { value: 'oil_tank', label: 'Cuve mazout', icon: '🛢️', unit: 'L' },
  { value: 'calorimeter', label: 'Calorimètre', icon: '🌡️', unit: 'kWh' },
  { value: 'other', label: 'Autre', icon: '📊', unit: '' },
]

// Types de champs pour les zones
const FIELD_TYPES = [
  { value: 'serialNumber', label: 'Numéro de compteur', icon: '🔢' },
  { value: 'ean', label: 'Code EAN', icon: '📊' },
  { value: 'readingSingle', label: 'Index', icon: '📈' },
  { value: 'readingDay', label: 'Index jour', icon: '☀️' },
  { value: 'readingNight', label: 'Index nuit', icon: '🌙' },
  { value: 'readingProduction', label: 'Index production', icon: '⬆️' },
  { value: 'subscribedPower', label: 'Puissance souscrite', icon: '⚡' },
]

// Étapes du workflow
type Step = 'upload' | 'analyze' | 'zones' | 'review'

interface AnalysisResult {
  type: string
  serialNumber: string
  serialNumberLocation: string
  index: string
  indexUnit: string
  indexNote: string
  model: string
}

export default function CreateMeterModelPage() {
  const router = useRouter()
  
  // Step management
  const [currentStep, setCurrentStep] = useState<Step>('upload')
  
  // Photo state
  const [photos, setPhotos] = useState<{ file: File; preview: string }[]>([])
  const [selectedPhotoIndex, setSelectedPhotoIndex] = useState(0)
  
  // Analysis state
  const [isAnalyzing, setIsAnalyzing] = useState(false)
  const [analysis, setAnalysis] = useState<AnalysisResult | null>(null)
  const [editableAnalysis, setEditableAnalysis] = useState({
    type: '',
    serialNumber: '',
    serialNumberLocation: '',
    index: '',
    indexUnit: '',
    indexNote: '',
    model: '',
  })
  const [analysisModified, setAnalysisModified] = useState(false)
  
  // Form state
  const [formData, setFormData] = useState({
    name: '',
    manufacturer: '',
    meterType: '',
    unit: '',
  })
  
  // Zones state
  const [zones, setZones] = useState<Zone[]>([])
  
  // Final description (generated by Claude, not editable)
  const [finalDescription, setFinalDescription] = useState('')
  const [isGeneratingFinal, setIsGeneratingFinal] = useState(false)
  
  // Saving state
  const [isSaving, setIsSaving] = useState(false)

  // Handle photo upload
  const handlePhotoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files || [])
    const newPhotos = files.map(file => ({
      file,
      preview: URL.createObjectURL(file),
    }))
    setPhotos(prev => [...prev, ...newPhotos])
  }

  const removePhoto = (index: number) => {
    setPhotos(prev => prev.filter((_, i) => i !== index))
    if (selectedPhotoIndex >= index && selectedPhotoIndex > 0) {
      setSelectedPhotoIndex(prev => prev - 1)
    }
  }

  // Analyze with Claude (simplified format)
  const analyzeWithClaude = async (includeCorrections: boolean = false) => {
    if (photos.length === 0) return
    
    setIsAnalyzing(true)
    
    try {
      // Convert photo to base64
      const photo = photos[0]
      const base64 = await new Promise<string>((resolve) => {
        const reader = new FileReader()
        reader.onloadend = () => resolve((reader.result as string).split(',')[1])
        reader.readAsDataURL(photo.file)
      })
      
      // Build request
      const requestBody: any = { 
        photo: base64,
        mode: 'simple', // Mode simplifié
      }
      
      if (includeCorrections) {
        requestBody.userCorrections = editableAnalysis
      }
      
      const response = await fetch('/api/analyze-meter', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(requestBody),
      })
      
      if (!response.ok) throw new Error('Analyse échouée')
      
      const result = await response.json()
      
      setAnalysis(result)
      setEditableAnalysis({
        type: result.type || '',
        serialNumber: result.serialNumber || '',
        serialNumberLocation: result.serialNumberLocation || '',
        index: result.index || '',
        indexUnit: result.indexUnit || '',
        indexNote: result.indexNote || '',
        model: result.model || '',
      })
      setAnalysisModified(false)
      
      // Update form with AI suggestions
      const meterType = METER_TYPES.find(t => 
        t.label.toLowerCase().includes(result.type?.toLowerCase()) ||
        result.type?.toLowerCase().includes(t.value.replace('_', ' '))
      )
      
      setFormData({
        name: result.model || '',
        manufacturer: result.model?.split(' ')[0] || '',
        meterType: meterType?.value || '',
        unit: result.indexUnit || meterType?.unit || '',
      })
      
      setCurrentStep('analyze')
      
    } catch (error) {
      console.error('Analysis error:', error)
      alert('Erreur lors de l\'analyse. Veuillez réessayer.')
    } finally {
      setIsAnalyzing(false)
    }
  }

  // Check if analysis was modified
  const checkAnalysisModified = (field: string, value: string) => {
    const newAnalysis = { ...editableAnalysis, [field]: value }
    setEditableAnalysis(newAnalysis)
    
    if (analysis) {
      const isModified = 
        newAnalysis.type !== analysis.type ||
        newAnalysis.serialNumber !== analysis.serialNumber ||
        newAnalysis.index !== analysis.index ||
        newAnalysis.model !== analysis.model
      setAnalysisModified(isModified)
    }
  }

  // Generate final description
  const generateFinalDescription = async () => {
    setIsGeneratingFinal(true)
    
    try {
      const photo = photos[0]
      const base64 = await new Promise<string>((resolve) => {
        const reader = new FileReader()
        reader.onloadend = () => resolve((reader.result as string).split(',')[1])
        reader.readAsDataURL(photo.file)
      })
      
      const response = await fetch('/api/generate-meter-description', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          photo: base64,
          name: formData.name,
          manufacturer: formData.manufacturer,
          meterType: formData.meterType,
          zones: zones.map(z => ({
            fieldType: z.fieldType,
            note: z.note,
            position: z.drawMode === 'rectangle' 
              ? { x: z.x, y: z.y, width: z.width, height: z.height }
              : { path: z.path },
          })),
          analysis: editableAnalysis,
        }),
      })
      
      if (!response.ok) throw new Error('Génération échouée')
      
      const result = await response.json()
      setFinalDescription(result.description)
      setCurrentStep('review')
      
    } catch (error) {
      console.error('Generation error:', error)
      alert('Erreur lors de la génération de la description.')
    } finally {
      setIsGeneratingFinal(false)
    }
  }

  // Save the model
  const saveModel = async () => {
    setIsSaving(true)
    
    try {
      // Upload photos to storage first
      const uploadedUrls: string[] = []
      
      for (const photo of photos) {
        const formDataUpload = new FormData()
        formDataUpload.append('file', photo.file)
        
        const uploadResponse = await fetch('/api/upload-meter-photo', {
          method: 'POST',
          body: formDataUpload,
        })
        
        if (uploadResponse.ok) {
          const { url } = await uploadResponse.json()
          uploadedUrls.push(url)
        }
      }
      
      // Create the model
      const response = await fetch('/api/meter-models', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: formData.name,
          manufacturer: formData.manufacturer,
          meter_type: formData.meterType,
          unit: formData.unit,
          ai_description: finalDescription,
          zones: zones.map(z => ({
            id: z.id,
            fieldType: z.fieldType,
            note: z.note,
            drawMode: z.drawMode,
            ...(z.drawMode === 'rectangle' ? {
              position: { x: z.x, y: z.y, width: z.width, height: z.height },
            } : {
              path: z.path,
            }),
          })),
          reference_photos: uploadedUrls,
          is_active: true,
        }),
      })
      
      if (!response.ok) {
        const error = await response.json()
        throw new Error(error.message || 'Sauvegarde échouée')
      }
      
      router.push('/dashboard/meters')
      
    } catch (error) {
      console.error('Save error:', error)
      alert('Erreur lors de la sauvegarde: ' + (error as Error).message)
    } finally {
      setIsSaving(false)
    }
  }

  // Update meter type and unit together
  const handleMeterTypeChange = (value: string) => {
    const type = METER_TYPES.find(t => t.value === value)
    setFormData(prev => ({
      ...prev,
      meterType: value,
      unit: type?.unit || prev.unit,
    }))
  }

  // Step indicators
  const steps = [
    { key: 'upload', label: '1. Photo' },
    { key: 'analyze', label: '2. Analyse' },
    { key: 'zones', label: '3. Zones' },
    { key: 'review', label: '4. Validation' },
  ]

  const currentStepIndex = steps.findIndex(s => s.key === currentStep)

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center gap-4">
        <Link href="/dashboard/meters">
          <Button variant="ghost" size="icon">
            <ArrowLeft className="w-5 h-5" />
          </Button>
        </Link>
        <div>
          <h1 className="text-2xl font-bold">Nouveau modèle de compteur</h1>
          <p className="text-gray-500">Workflow assisté par Claude AI</p>
        </div>
      </div>

      {/* Step indicator */}
      <div className="flex items-center gap-2">
        {steps.map((step, index) => (
          <div key={step.key} className="flex items-center">
            <div className={`px-4 py-2 rounded-full text-sm font-medium transition-all ${
              index < currentStepIndex 
                ? 'bg-teal-500 text-white'
                : index === currentStepIndex 
                  ? 'bg-teal-100 text-teal-700 ring-2 ring-teal-500' 
                  : 'bg-gray-100 text-gray-400'
            }`}>
              {step.label}
            </div>
            {index < steps.length - 1 && (
              <div className={`w-8 h-0.5 mx-1 ${
                index < currentStepIndex ? 'bg-teal-500' : 'bg-gray-200'
              }`} />
            )}
          </div>
        ))}
      </div>

      {/* Step content */}
      <div className="bg-white rounded-xl border p-6">
        
        {/* STEP 1: Upload photos */}
        {currentStep === 'upload' && (
          <div className="space-y-6">
            <div>
              <h2 className="text-lg font-semibold mb-2">Photo du compteur</h2>
              <p className="text-gray-500">
                Prenez une photo claire et bien cadrée du compteur
              </p>
            </div>

            <div className="flex flex-wrap gap-4">
              {photos.map((photo, index) => (
                <div key={index} className="relative group">
                  <img
                    src={photo.preview}
                    alt={`Photo ${index + 1}`}
                    className={`w-48 h-48 object-cover rounded-lg border-2 cursor-pointer ${
                      selectedPhotoIndex === index ? 'border-teal-500' : 'border-gray-200'
                    }`}
                    onClick={() => setSelectedPhotoIndex(index)}
                  />
                  <button
                    onClick={() => removePhoto(index)}
                    className="absolute -top-2 -right-2 bg-red-500 text-white rounded-full p-1 opacity-0 group-hover:opacity-100 transition-opacity"
                  >
                    <X className="w-4 h-4" />
                  </button>
                </div>
              ))}

              {photos.length === 0 && (
                <label className="w-48 h-48 border-2 border-dashed border-gray-300 rounded-lg flex flex-col items-center justify-center cursor-pointer hover:border-teal-500 hover:bg-teal-50 transition-colors">
                  <Upload className="w-10 h-10 text-gray-400" />
                  <span className="text-sm text-gray-500 mt-2">Ajouter une photo</span>
                  <input
                    type="file"
                    accept="image/*"
                    className="hidden"
                    onChange={handlePhotoUpload}
                  />
                </label>
              )}
            </div>

            <div className="flex justify-end">
              <Button
                onClick={() => analyzeWithClaude(false)}
                disabled={photos.length === 0 || isAnalyzing}
                size="lg"
                className="bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600"
              >
                {isAnalyzing ? (
                  <>
                    <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                    Analyse en cours...
                  </>
                ) : (
                  <>
                    <Sparkles className="w-5 h-5 mr-2" />
                    Analyser avec Claude
                  </>
                )}
              </Button>
            </div>
          </div>
        )}

        {/* STEP 2: Analyze & Edit */}
        {currentStep === 'analyze' && (
          <div className="space-y-6">
            <div className="flex items-start justify-between">
              <div>
                <h2 className="text-lg font-semibold mb-2">Analyse du compteur</h2>
                <p className="text-gray-500">
                  Vérifiez et corrigez si nécessaire
                </p>
              </div>
              
              {analysisModified && (
                <Button
                  onClick={() => analyzeWithClaude(true)}
                  disabled={isAnalyzing}
                  variant="outline"
                  className="border-purple-300 text-purple-600 hover:bg-purple-50"
                >
                  {isAnalyzing ? (
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  ) : (
                    <RefreshCw className="w-4 h-4 mr-2" />
                  )}
                  Régénérer
                </Button>
              )}
            </div>

            <div className="grid grid-cols-2 gap-6">
              {/* Photo preview */}
              <div>
                <img
                  src={photos[0]?.preview}
                  alt="Compteur"
                  className="w-full rounded-lg border"
                />
              </div>

              {/* Analysis fields */}
              <div className="space-y-4">
                {/* Type */}
                <div className="bg-gray-50 rounded-lg p-4">
                  <Label className="text-sm text-gray-500">TYPE</Label>
                  <Input
                    value={editableAnalysis.type}
                    onChange={(e) => checkAnalysisModified('type', e.target.value)}
                    className="mt-1 text-lg font-semibold border-0 bg-transparent p-0 h-auto focus-visible:ring-0"
                    placeholder="Gaz, Eau, Électricité..."
                  />
                </div>

                {/* Numéro de compteur */}
                <div className="bg-gray-50 rounded-lg p-4">
                  <Label className="text-sm text-gray-500">NUMÉRO DE COMPTEUR</Label>
                  <Input
                    value={editableAnalysis.serialNumber}
                    onChange={(e) => checkAnalysisModified('serialNumber', e.target.value)}
                    className="mt-1 text-lg font-mono border-0 bg-transparent p-0 h-auto focus-visible:ring-0"
                    placeholder="Ex: 25933911"
                  />
                  <Input
                    value={editableAnalysis.serialNumberLocation}
                    onChange={(e) => checkAnalysisModified('serialNumberLocation', e.target.value)}
                    className="mt-2 text-sm text-gray-500 border-0 bg-transparent p-0 h-auto focus-visible:ring-0"
                    placeholder="Où se trouve-t-il ? (ex: étiquette bleue en bas)"
                  />
                </div>

                {/* Index */}
                <div className="bg-gray-50 rounded-lg p-4">
                  <Label className="text-sm text-gray-500">INDEX</Label>
                  <div className="flex items-baseline gap-2 mt-1">
                    <Input
                      value={editableAnalysis.index}
                      onChange={(e) => checkAnalysisModified('index', e.target.value)}
                      className="text-lg font-mono border-0 bg-transparent p-0 h-auto focus-visible:ring-0 flex-1"
                      placeholder="Ex: 000001875"
                    />
                    <Input
                      value={editableAnalysis.indexUnit}
                      onChange={(e) => checkAnalysisModified('indexUnit', e.target.value)}
                      className="text-lg border-0 bg-transparent p-0 h-auto focus-visible:ring-0 w-16"
                      placeholder="m³"
                    />
                  </div>
                  <Textarea
                    value={editableAnalysis.indexNote}
                    onChange={(e) => checkAnalysisModified('indexNote', e.target.value)}
                    className="mt-2 text-sm text-gray-500 border-0 bg-transparent p-0 min-h-0 focus-visible:ring-0 resize-none"
                    placeholder="Comment lire l'index ? (rouleaux noirs/rouges, décimales...)"
                    rows={2}
                  />
                </div>

                {/* Modèle */}
                <div className="bg-gray-50 rounded-lg p-4">
                  <Label className="text-sm text-gray-500">MODÈLE</Label>
                  <Input
                    value={editableAnalysis.model}
                    onChange={(e) => checkAnalysisModified('model', e.target.value)}
                    className="mt-1 text-lg border-0 bg-transparent p-0 h-auto focus-visible:ring-0"
                    placeholder="Ex: Itron G4 RF1"
                  />
                </div>
              </div>
            </div>

            {/* Form fields */}
            <div className="border-t pt-6">
              <h3 className="font-medium mb-4">Informations du modèle</h3>
              <div className="grid grid-cols-4 gap-4">
                <div className="space-y-2">
                  <Label>Nom *</Label>
                  <Input
                    value={formData.name}
                    onChange={(e) => setFormData(prev => ({ ...prev, name: e.target.value }))}
                    placeholder="Itron G4 RF1"
                  />
                </div>
                
                <div className="space-y-2">
                  <Label>Fabricant</Label>
                  <Input
                    value={formData.manufacturer}
                    onChange={(e) => setFormData(prev => ({ ...prev, manufacturer: e.target.value }))}
                    placeholder="Itron"
                  />
                </div>
                
                <div className="space-y-2">
                  <Label>Type *</Label>
                  <Select value={formData.meterType} onValueChange={handleMeterTypeChange}>
                    <SelectTrigger>
                      <SelectValue placeholder="Sélectionner..." />
                    </SelectTrigger>
                    <SelectContent>
                      {METER_TYPES.map(type => (
                        <SelectItem key={type.value} value={type.value}>
                          <span className="flex items-center gap-2">
                            <span>{type.icon}</span>
                            <span>{type.label}</span>
                          </span>
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                
                <div className="space-y-2">
                  <Label>Unité</Label>
                  <Input
                    value={formData.unit}
                    onChange={(e) => setFormData(prev => ({ ...prev, unit: e.target.value }))}
                    placeholder="m³"
                  />
                </div>
              </div>
            </div>

            <div className="flex justify-between pt-4">
              <Button variant="outline" onClick={() => setCurrentStep('upload')}>
                Retour
              </Button>
              <Button 
                onClick={() => setCurrentStep('zones')}
                disabled={!formData.name || !formData.meterType}
              >
                Continuer
              </Button>
            </div>
          </div>
        )}

        {/* STEP 3: Zone Mapping */}
        {currentStep === 'zones' && photos.length > 0 && (
          <div className="space-y-6">
            <div>
              <h2 className="text-lg font-semibold mb-2">Zones de lecture</h2>
              <p className="text-gray-500">
                Dessinez les zones pour indiquer à Claude où trouver les informations
              </p>
            </div>

            <ZoneMapper
              imageUrl={photos[selectedPhotoIndex].preview}
              zones={zones}
              onZonesChange={setZones}
              fieldTypes={FIELD_TYPES}
            />

            <div className="flex justify-between pt-4 border-t">
              <Button variant="outline" onClick={() => setCurrentStep('analyze')}>
                Retour
              </Button>
              <Button 
                onClick={generateFinalDescription}
                disabled={zones.length === 0 || isGeneratingFinal}
              >
                {isGeneratingFinal ? (
                  <>
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    Génération...
                  </>
                ) : (
                  'Générer la description'
                )}
              </Button>
            </div>
          </div>
        )}

        {/* STEP 4: Review & Save */}
        {currentStep === 'review' && (
          <div className="space-y-6">
            <div>
              <h2 className="text-lg font-semibold mb-2">Validation finale</h2>
              <p className="text-gray-500">
                Vérifiez avant de créer le modèle
              </p>
            </div>

            <div className="grid grid-cols-2 gap-6">
              {/* Summary */}
              <div className="space-y-4">
                <div className="bg-gray-50 rounded-lg p-4">
                  <h3 className="font-medium mb-3">Récapitulatif</h3>
                  <dl className="space-y-2 text-sm">
                    <div className="flex justify-between">
                      <dt className="text-gray-500">Nom:</dt>
                      <dd className="font-medium">{formData.name}</dd>
                    </div>
                    <div className="flex justify-between">
                      <dt className="text-gray-500">Fabricant:</dt>
                      <dd>{formData.manufacturer || '-'}</dd>
                    </div>
                    <div className="flex justify-between">
                      <dt className="text-gray-500">Type:</dt>
                      <dd>
                        {METER_TYPES.find(t => t.value === formData.meterType)?.icon}{' '}
                        {METER_TYPES.find(t => t.value === formData.meterType)?.label}
                      </dd>
                    </div>
                    <div className="flex justify-between">
                      <dt className="text-gray-500">Unité:</dt>
                      <dd>{formData.unit}</dd>
                    </div>
                    <div className="flex justify-between">
                      <dt className="text-gray-500">Zones:</dt>
                      <dd>{zones.length} zone(s)</dd>
                    </div>
                  </dl>
                </div>

                <div className="bg-gray-50 rounded-lg p-4">
                  <h3 className="font-medium mb-3">Zones définies</h3>
                  <ul className="space-y-2 text-sm">
                    {zones.map(zone => (
                      <li key={zone.id} className="flex items-start gap-2">
                        <span>{FIELD_TYPES.find(f => f.value === zone.fieldType)?.icon}</span>
                        <div>
                          <span className="font-medium">
                            {FIELD_TYPES.find(f => f.value === zone.fieldType)?.label}
                          </span>
                          {zone.note && (
                            <p className="text-gray-500 text-xs mt-0.5">{zone.note}</p>
                          )}
                        </div>
                      </li>
                    ))}
                  </ul>
                </div>

                <img
                  src={photos[0]?.preview}
                  alt="Référence"
                  className="w-full rounded-lg border"
                />
              </div>

              {/* Final description */}
              <div>
                <div className="bg-purple-50 border border-purple-200 rounded-lg p-4 h-full">
                  <div className="flex items-center gap-2 mb-3">
                    <Sparkles className="w-4 h-4 text-purple-500" />
                    <span className="font-medium text-purple-700">Description pour Claude</span>
                  </div>
                  <p className="text-xs text-purple-500 mb-3">
                    Cette description sera utilisée par Claude pour reconnaître ce type de compteur lors des futurs scans. Elle n'est pas modifiable.
                  </p>
                  <div className="bg-white rounded p-3 text-sm text-gray-700 whitespace-pre-wrap max-h-96 overflow-y-auto">
                    {finalDescription}
                  </div>
                </div>
              </div>
            </div>

            <div className="flex justify-between pt-4 border-t">
              <Button variant="outline" onClick={() => setCurrentStep('zones')}>
                Retour
              </Button>
              <div className="flex gap-3">
                <Button variant="outline" onClick={() => router.push('/dashboard/meters')}>
                  Annuler
                </Button>
                <Button 
                  onClick={saveModel}
                  disabled={isSaving}
                  className="bg-teal-600 hover:bg-teal-700"
                >
                  {isSaving ? (
                    <>
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                      Création...
                    </>
                  ) : (
                    <>
                      <Check className="w-4 h-4 mr-2" />
                      Créer le modèle
                    </>
                  )}
                </Button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
