"use client"

import { useState, useCallback } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, Upload, Sparkles, Loader2, Check, X, RefreshCw } from 'lucide-react'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { ZoneMapper, Zone } from '@/components/zone-mapper'

// Types de compteurs
const METER_TYPES = [
  { value: 'water_general', label: 'Eau - Général', icon: '💧', unit: 'm³' },
  { value: 'water_passage', label: 'Eau - Passage', icon: '🚿', unit: 'm³' },
  { value: 'electricity', label: 'Électricité', icon: '⚡', unit: 'kWh' },
  { value: 'gas', label: 'Gaz', icon: '🔥', unit: 'm³' },
  { value: 'oil_tank', label: 'Cuve mazout', icon: '🛢️', unit: 'L' },
  { value: 'calorimeter', label: 'Calorimètre', icon: '🌡️', unit: 'kWh' },
  { value: 'other', label: 'Autre', icon: '📊', unit: '' },
]

// Types de champs
const FIELD_TYPES = [
  { value: 'serialNumber', label: 'Numéro de compteur', icon: '🔢' },
  { value: 'ean', label: 'Code EAN', icon: '📊' },
  { value: 'readingSingle', label: 'Index unique', icon: '📈' },
  { value: 'readingDay', label: 'Index jour / heures pleines', icon: '☀️' },
  { value: 'readingNight', label: 'Index nuit / heures creuses', icon: '🌙' },
  { value: 'readingExclusiveNight', label: 'Index exclusif nuit', icon: '🌑' },
  { value: 'readingProduction', label: 'Index production', icon: '⬆️' },
  { value: 'subscribedPower', label: 'Puissance souscrite', icon: '⚡' },
  { value: 'custom', label: 'Champ personnalisé', icon: '✏️' },
]

// Étapes du workflow
type Step = 'upload' | 'analyze' | 'zones' | 'review'

interface AnalysisResult {
  name: string
  manufacturer: string
  meterType: string
  description: string
  rawAnalysis: string
}

export default function CreateMeterModelPage() {
  const router = useRouter()
  
  // Step management
  const [currentStep, setCurrentStep] = useState<Step>('upload')
  
  // Photo state
  const [photos, setPhotos] = useState<{ file: File; preview: string }[]>([])
  const [selectedPhotoIndex, setSelectedPhotoIndex] = useState(0)
  
  // Analysis state
  const [isAnalyzing, setIsAnalyzing] = useState(false)
  const [analysis, setAnalysis] = useState<AnalysisResult | null>(null)
  const [editedAnalysis, setEditedAnalysis] = useState('')
  const [analysisModified, setAnalysisModified] = useState(false)
  
  // Form state
  const [formData, setFormData] = useState({
    name: '',
    manufacturer: '',
    meterType: '',
    unit: '',
  })
  
  // Zones state
  const [zones, setZones] = useState<Zone[]>([])
  
  // Final description (generated by Claude, not editable)
  const [finalDescription, setFinalDescription] = useState('')
  const [isGeneratingFinal, setIsGeneratingFinal] = useState(false)
  
  // Saving state
  const [isSaving, setIsSaving] = useState(false)

  // Handle photo upload
  const handlePhotoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files || [])
    const newPhotos = files.map(file => ({
      file,
      preview: URL.createObjectURL(file),
    }))
    setPhotos(prev => [...prev, ...newPhotos])
  }

  const removePhoto = (index: number) => {
    setPhotos(prev => prev.filter((_, i) => i !== index))
    if (selectedPhotoIndex >= index && selectedPhotoIndex > 0) {
      setSelectedPhotoIndex(prev => prev - 1)
    }
  }

  // Analyze with Claude
  const analyzeWithClaude = async (includeCorrections: boolean = false) => {
    if (photos.length === 0) return
    
    setIsAnalyzing(true)
    
    try {
      // Convert photos to base64
      const photoPromises = photos.slice(0, 4).map(photo => {
        return new Promise<string>((resolve) => {
          const reader = new FileReader()
          reader.onloadend = () => {
            const base64 = (reader.result as string).split(',')[1]
            resolve(base64)
          }
          reader.readAsDataURL(photo.file)
        })
      })
      
      const base64Photos = await Promise.all(photoPromises)
      
      // Build request with optional corrections
      const requestBody: any = { photos: base64Photos }
      
      if (includeCorrections && analysisModified) {
        requestBody.userCorrections = {
          analysis: editedAnalysis,
          name: formData.name,
          manufacturer: formData.manufacturer,
          meterType: formData.meterType,
        }
      }
      
      const response = await fetch('/api/analyze-meter', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(requestBody),
      })
      
      if (!response.ok) throw new Error('Analyse échouée')
      
      const result = await response.json()
      
      setAnalysis(result)
      setEditedAnalysis(result.rawAnalysis)
      setAnalysisModified(false)
      
      // Update form with AI suggestions
      setFormData({
        name: result.name || '',
        manufacturer: result.manufacturer || '',
        meterType: result.meterType || '',
        unit: METER_TYPES.find(t => t.value === result.meterType)?.unit || '',
      })
      
      // Auto-create zones from AI suggestions if available
      if (result.suggestedZones && result.suggestedZones.length > 0) {
        const newZones: Zone[] = result.suggestedZones.map((zone: any, index: number) => ({
          id: `zone-${Date.now()}-${index}`,
          fieldType: zone.fieldType,
          label: zone.label || '',
          x: 10 + (index * 5), // Default positions (will be adjusted by user)
          y: 10 + (index * 15),
          width: 30,
          height: 10,
          hasDecimals: zone.hasDecimals || false,
          decimalDigits: zone.decimalDigits,
        }))
        setZones(newZones)
      }
      
      setCurrentStep('analyze')
      
    } catch (error) {
      console.error('Analysis error:', error)
      alert('Erreur lors de l\'analyse. Veuillez réessayer.')
    } finally {
      setIsAnalyzing(false)
    }
  }

  // Regenerate analysis with user corrections
  const regenerateAnalysis = () => {
    analyzeWithClaude(true)
  }

  // Handle analysis text change
  const handleAnalysisChange = (value: string) => {
    setEditedAnalysis(value)
    setAnalysisModified(value !== analysis?.rawAnalysis)
  }

  // Generate final description
  const generateFinalDescription = async () => {
    setIsGeneratingFinal(true)
    
    try {
      // Convert first photo to base64
      const photo = photos[0]
      const base64 = await new Promise<string>((resolve) => {
        const reader = new FileReader()
        reader.onloadend = () => resolve((reader.result as string).split(',')[1])
        reader.readAsDataURL(photo.file)
      })
      
      const response = await fetch('/api/generate-meter-description', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          photo: base64,
          name: formData.name,
          manufacturer: formData.manufacturer,
          meterType: formData.meterType,
          zones: zones.map(z => ({
            fieldType: z.fieldType,
            label: z.label,
            position: { x: z.x, y: z.y, width: z.width, height: z.height },
            hasDecimals: z.hasDecimals,
            decimalDigits: z.decimalDigits,
          })),
          userAnalysis: editedAnalysis,
        }),
      })
      
      if (!response.ok) throw new Error('Génération échouée')
      
      const result = await response.json()
      setFinalDescription(result.description)
      setCurrentStep('review')
      
    } catch (error) {
      console.error('Generation error:', error)
      alert('Erreur lors de la génération de la description.')
    } finally {
      setIsGeneratingFinal(false)
    }
  }

  // Save the model
  const saveModel = async () => {
    setIsSaving(true)
    
    try {
      // Upload photos to storage first
      const uploadedUrls: string[] = []
      
      for (const photo of photos) {
        const formData = new FormData()
        formData.append('file', photo.file)
        
        const uploadResponse = await fetch('/api/upload-meter-photo', {
          method: 'POST',
          body: formData,
        })
        
        if (uploadResponse.ok) {
          const { url } = await uploadResponse.json()
          uploadedUrls.push(url)
        }
      }
      
      // Create the model
      const response = await fetch('/api/meter-models', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: formData.name,
          manufacturer: formData.manufacturer,
          meter_type: formData.meterType,
          unit: formData.unit,
          ai_description: finalDescription,
          zones: zones.map(z => ({
            id: z.id,
            fieldType: z.fieldType,
            label: z.label,
            position: { x: z.x, y: z.y, width: z.width, height: z.height },
            hasDecimals: z.hasDecimals,
            decimalDigits: z.decimalDigits,
          })),
          reference_photos: uploadedUrls,
          is_active: true,
        }),
      })
      
      if (!response.ok) throw new Error('Sauvegarde échouée')
      
      router.push('/dashboard/meters')
      
    } catch (error) {
      console.error('Save error:', error)
      alert('Erreur lors de la sauvegarde.')
    } finally {
      setIsSaving(false)
    }
  }

  // Update meter type and unit together
  const handleMeterTypeChange = (value: string) => {
    const type = METER_TYPES.find(t => t.value === value)
    setFormData(prev => ({
      ...prev,
      meterType: value,
      unit: type?.unit || '',
    }))
  }

  // Step indicators
  const steps = [
    { key: 'upload', label: '1. Photos', icon: Upload },
    { key: 'analyze', label: '2. Analyse', icon: Sparkles },
    { key: 'zones', label: '3. Zones', icon: Check },
    { key: 'review', label: '4. Validation', icon: Check },
  ]

  const currentStepIndex = steps.findIndex(s => s.key === currentStep)

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center gap-4">
        <Link href="/dashboard/meters">
          <Button variant="ghost" size="icon">
            <ArrowLeft className="w-5 h-5" />
          </Button>
        </Link>
        <div>
          <h1 className="text-2xl font-bold">Nouveau modèle de compteur</h1>
          <p className="text-gray-500">Workflow assisté par Claude AI</p>
        </div>
      </div>

      {/* Step indicator */}
      <div className="flex items-center justify-between max-w-2xl">
        {steps.map((step, index) => (
          <div key={step.key} className="flex items-center">
            <div className={`flex items-center gap-2 px-4 py-2 rounded-full ${
              index <= currentStepIndex 
                ? 'bg-teal-100 text-teal-700' 
                : 'bg-gray-100 text-gray-400'
            }`}>
              <step.icon className="w-4 h-4" />
              <span className="text-sm font-medium">{step.label}</span>
            </div>
            {index < steps.length - 1 && (
              <div className={`w-8 h-0.5 mx-2 ${
                index < currentStepIndex ? 'bg-teal-500' : 'bg-gray-200'
              }`} />
            )}
          </div>
        ))}
      </div>

      {/* Step content */}
      <div className="bg-white rounded-xl border p-6">
        
        {/* STEP 1: Upload photos */}
        {currentStep === 'upload' && (
          <div className="space-y-6">
            <div>
              <h2 className="text-lg font-semibold mb-2">Photos de référence</h2>
              <p className="text-gray-500">
                Ajoutez des photos claires du compteur sous différents angles
              </p>
            </div>

            <div className="flex flex-wrap gap-4">
              {photos.map((photo, index) => (
                <div key={index} className="relative group">
                  <img
                    src={photo.preview}
                    alt={`Photo ${index + 1}`}
                    className={`w-40 h-40 object-cover rounded-lg border-2 cursor-pointer ${
                      selectedPhotoIndex === index ? 'border-teal-500' : 'border-gray-200'
                    }`}
                    onClick={() => setSelectedPhotoIndex(index)}
                  />
                  <button
                    onClick={() => removePhoto(index)}
                    className="absolute -top-2 -right-2 bg-red-500 text-white rounded-full p-1 opacity-0 group-hover:opacity-100 transition-opacity"
                  >
                    <X className="w-4 h-4" />
                  </button>
                </div>
              ))}

              <label className="w-40 h-40 border-2 border-dashed border-gray-300 rounded-lg flex flex-col items-center justify-center cursor-pointer hover:border-teal-500 hover:bg-teal-50 transition-colors">
                <Upload className="w-8 h-8 text-gray-400" />
                <span className="text-sm text-gray-500 mt-2">Ajouter</span>
                <input
                  type="file"
                  accept="image/*"
                  multiple
                  className="hidden"
                  onChange={handlePhotoUpload}
                />
              </label>
            </div>

            <div className="flex justify-end">
              <Button
                onClick={() => analyzeWithClaude(false)}
                disabled={photos.length === 0 || isAnalyzing}
                className="bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600"
              >
                {isAnalyzing ? (
                  <>
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    Analyse en cours...
                  </>
                ) : (
                  <>
                    <Sparkles className="w-4 h-4 mr-2" />
                    Analyser avec Claude
                  </>
                )}
              </Button>
            </div>
          </div>
        )}

        {/* STEP 2: Analyze & Edit */}
        {currentStep === 'analyze' && analysis && (
          <div className="space-y-6">
            <div className="flex items-start justify-between">
              <div>
                <h2 className="text-lg font-semibold mb-2">Analyse Claude</h2>
                <p className="text-gray-500">
                  Vérifiez et corrigez l'analyse si nécessaire
                </p>
              </div>
              
              {analysisModified && (
                <Button
                  onClick={regenerateAnalysis}
                  disabled={isAnalyzing}
                  variant="outline"
                  className="border-purple-300 text-purple-600 hover:bg-purple-50"
                >
                  {isAnalyzing ? (
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  ) : (
                    <RefreshCw className="w-4 h-4 mr-2" />
                  )}
                  Régénérer l'analyse
                </Button>
              )}
            </div>

            {/* Editable analysis */}
            <div className="bg-purple-50 border border-purple-200 rounded-lg p-4">
              <div className="flex items-center gap-2 mb-3">
                <Sparkles className="w-4 h-4 text-purple-500" />
                <span className="font-medium text-purple-700">Analyse (modifiable)</span>
                {analysisModified && (
                  <span className="text-xs bg-orange-100 text-orange-600 px-2 py-0.5 rounded-full">
                    Modifié
                  </span>
                )}
              </div>
              <Textarea
                value={editedAnalysis}
                onChange={(e) => handleAnalysisChange(e.target.value)}
                className="min-h-[120px] bg-white"
              />
            </div>

            {/* Form fields */}
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label>Nom du modèle *</Label>
                <Input
                  value={formData.name}
                  onChange={(e) => setFormData(prev => ({ ...prev, name: e.target.value }))}
                  placeholder="Ex: Itron Aquadis+"
                />
              </div>
              
              <div className="space-y-2">
                <Label>Fabricant</Label>
                <Input
                  value={formData.manufacturer}
                  onChange={(e) => setFormData(prev => ({ ...prev, manufacturer: e.target.value }))}
                  placeholder="Ex: Itron"
                />
              </div>
              
              <div className="space-y-2">
                <Label>Type de compteur *</Label>
                <Select value={formData.meterType} onValueChange={handleMeterTypeChange}>
                  <SelectTrigger>
                    <SelectValue placeholder="Sélectionner..." />
                  </SelectTrigger>
                  <SelectContent>
                    {METER_TYPES.map(type => (
                      <SelectItem key={type.value} value={type.value}>
                        <span className="flex items-center gap-2">
                          <span>{type.icon}</span>
                          <span>{type.label}</span>
                        </span>
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              
              <div className="space-y-2">
                <Label>Unité</Label>
                <Input
                  value={formData.unit}
                  onChange={(e) => setFormData(prev => ({ ...prev, unit: e.target.value }))}
                  placeholder="Ex: m³, kWh"
                />
              </div>
            </div>

            <div className="flex justify-between">
              <Button variant="outline" onClick={() => setCurrentStep('upload')}>
                Retour
              </Button>
              <Button 
                onClick={() => setCurrentStep('zones')}
                disabled={!formData.name || !formData.meterType}
              >
                Continuer vers les zones
              </Button>
            </div>
          </div>
        )}

        {/* STEP 3: Zone Mapping */}
        {currentStep === 'zones' && photos.length > 0 && (
          <div className="space-y-6">
            <div>
              <h2 className="text-lg font-semibold mb-2">Zones de lecture</h2>
              <p className="text-gray-500">
                Dessinez les zones sur l'image et assignez-leur un type de champ
              </p>
            </div>

            <ZoneMapper
              imageUrl={photos[selectedPhotoIndex].preview}
              zones={zones}
              onZonesChange={setZones}
              fieldTypes={FIELD_TYPES}
            />

            {/* Photo selector if multiple photos */}
            {photos.length > 1 && (
              <div className="flex gap-2">
                <span className="text-sm text-gray-500 mr-2">Photo:</span>
                {photos.map((photo, index) => (
                  <button
                    key={index}
                    onClick={() => setSelectedPhotoIndex(index)}
                    className={`w-12 h-12 rounded border-2 overflow-hidden ${
                      selectedPhotoIndex === index ? 'border-teal-500' : 'border-gray-200'
                    }`}
                  >
                    <img src={photo.preview} alt="" className="w-full h-full object-cover" />
                  </button>
                ))}
              </div>
            )}

            <div className="flex justify-between">
              <Button variant="outline" onClick={() => setCurrentStep('analyze')}>
                Retour
              </Button>
              <Button 
                onClick={generateFinalDescription}
                disabled={zones.length === 0 || isGeneratingFinal}
              >
                {isGeneratingFinal ? (
                  <>
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    Génération...
                  </>
                ) : (
                  'Générer la description finale'
                )}
              </Button>
            </div>
          </div>
        )}

        {/* STEP 4: Review & Save */}
        {currentStep === 'review' && (
          <div className="space-y-6">
            <div>
              <h2 className="text-lg font-semibold mb-2">Validation finale</h2>
              <p className="text-gray-500">
                Vérifiez les informations avant de créer le modèle
              </p>
            </div>

            {/* Summary */}
            <div className="grid grid-cols-2 gap-6">
              <div className="space-y-4">
                <div className="bg-gray-50 rounded-lg p-4">
                  <h3 className="font-medium mb-3">Informations</h3>
                  <dl className="space-y-2 text-sm">
                    <div className="flex justify-between">
                      <dt className="text-gray-500">Nom:</dt>
                      <dd className="font-medium">{formData.name}</dd>
                    </div>
                    <div className="flex justify-between">
                      <dt className="text-gray-500">Fabricant:</dt>
                      <dd>{formData.manufacturer || '-'}</dd>
                    </div>
                    <div className="flex justify-between">
                      <dt className="text-gray-500">Type:</dt>
                      <dd>{METER_TYPES.find(t => t.value === formData.meterType)?.label}</dd>
                    </div>
                    <div className="flex justify-between">
                      <dt className="text-gray-500">Unité:</dt>
                      <dd>{formData.unit}</dd>
                    </div>
                    <div className="flex justify-between">
                      <dt className="text-gray-500">Zones:</dt>
                      <dd>{zones.length} zone(s) définie(s)</dd>
                    </div>
                  </dl>
                </div>

                <div className="bg-gray-50 rounded-lg p-4">
                  <h3 className="font-medium mb-3">Zones de lecture</h3>
                  <ul className="space-y-2 text-sm">
                    {zones.map(zone => (
                      <li key={zone.id} className="flex items-center gap-2">
                        <span className="w-3 h-3 rounded" style={{
                          backgroundColor: FIELD_TYPES.find(f => f.value === zone.fieldType)?.icon ? '#10b981' : '#6b7280'
                        }} />
                        <span>{zone.label || FIELD_TYPES.find(f => f.value === zone.fieldType)?.label}</span>
                        {zone.hasDecimals && (
                          <span className="text-xs text-gray-400">({zone.decimalDigits} déc.)</span>
                        )}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              <div className="space-y-4">
                <div className="bg-purple-50 border border-purple-200 rounded-lg p-4">
                  <div className="flex items-center gap-2 mb-3">
                    <Sparkles className="w-4 h-4 text-purple-500" />
                    <span className="font-medium text-purple-700">Description pour Claude</span>
                    <span className="text-xs text-purple-500">(non modifiable)</span>
                  </div>
                  <p className="text-sm text-gray-700 whitespace-pre-wrap">
                    {finalDescription}
                  </p>
                </div>

                {photos.length > 0 && (
                  <div>
                    <h3 className="font-medium mb-2">Photo de référence</h3>
                    <img
                      src={photos[0].preview}
                      alt="Référence"
                      className="w-full max-w-xs rounded-lg border"
                    />
                  </div>
                )}
              </div>
            </div>

            <div className="flex justify-between pt-4 border-t">
              <Button variant="outline" onClick={() => setCurrentStep('zones')}>
                Retour
              </Button>
              <div className="flex gap-3">
                <Button variant="outline" onClick={() => router.push('/dashboard/meters')}>
                  Annuler
                </Button>
                <Button 
                  onClick={saveModel}
                  disabled={isSaving}
                  className="bg-teal-600 hover:bg-teal-700"
                >
                  {isSaving ? (
                    <>
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                      Création...
                    </>
                  ) : (
                    <>
                      <Check className="w-4 h-4 mr-2" />
                      Créer le modèle
                    </>
                  )}
                </Button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
